### ISSUE TITLE
API Discussion

### ISSUE THREAD

**Issue by BrunoSanchez** [vcristiani/galaxy-chop#25]
#### This issue is dedicated specifically to the API design discussion.

This topic is _extremely_ relevant and critical for the further development of this software project.
We know now that the used datasets should look like the data samples presented in https://github.com/vcristiani/galaxy-chop/pull/24/commits/2fa19f4179f6ecf04461c4b8a9136ae0d3bda82c .

However, we still would like to define *what is exactly the desired behaviour and user interface of this project?*

I think this question is related to several other matters:
- Which users are we pointing to?
- What is the exact level of flexibility that we are able to sustain?
- Under the light of potential provided answers for the questions above, what is the product/service that we are commiting to deliver? What are the guarantees that we extend on our software?

Let the exchange of opinions  get started with this issue.

**Comment by vcristiani** [comment]
I would like us to think about this from an object orientation point of view. Let's define a galaxy class, within which we can do everything related to the calculation of the dynamic variables that come into play in the decomposition. And then a Model class, where all the methods of dynamic decomposition are involved and that allows to make an easy configuration of each one. This would allow not only to separate in components the stars of a "galaxy" object, but also to use the instance of the model to separate the gas. Or you could also use a mock, create a "galaxy" object, and use that to create the "Model" object and use that to make the decomposition of simulation galaxies.

**Comment by vcristiani** [comment]
So that it does not become complicated, we can start thinking that the data we have corresponds only to galaxies with positions and velocities already corrected, and then if it gives time we add the reading part of the simulation.

**Comment by RafaelPignata622** [comment]
**About Bruno's questions:**

-Which users are we pointing to?
I'm not from the area, but meybe the users that we need to target for the moments are only the users from the most famous simulation, thinking about the data imput format. 
 
-What is the exact level of flexibility that we are able to sustain?
Flexibility in the way that the users can interact? (maybe that is not the word) 
Bruno's idea of the thing that the user can create his "own" class in the input data format thing ? That kind of flexibility ?

Under the light of potential provided answers for the questions above, what is the product/service that we are committing to deliver? What are the guarantees that we extend on our software?

Again, I'm talking out of my area, but maybe guarantees consistency and variety. 

I meen, that always, with the same data, the results are the same with one method. And variety, a "large" (is not a need to be crazy) variety of descompositions methods

**About Vale's comment:**

I think that defining a galaxy class for "preparations of the dynamics variables" on the one hand and a model class for the dynamic decomposition on the other is a clean way to think the code. 

But now, every dynamic decomposition method it's going to be a class that inherits from Model class? that's going to be the idea?

**Comment by vcristiani** [comment]
I like the idea of adding the possibility of reading the data of the particles of the galaxy directly from the simulation and extracting the data from it. However, for simplicity, I think that for now, we should think that the input parameters come from a file with the stars, one with the gas (if the galaxy has one), and one with DM.

> _I think that defining a galaxy class for "preparations of the dynamics variables" on the one hand and a model class for the dynamic decomposition on the other is a clean way to think the code.
> But now, every dynamic decomposition method it's going to be a class that inherits from Model class? that's going to be the idea?_


That would be the idea. I discussed with Juan everything we have been talking about. Of all the ways of looking at the problem from which the project emerged, the one that convinced me the most was that.

**Comment by leliel12** [comment]
FYC: https://herbertograca.com/2018/09/12/4-aristocracy-democracy-and-system-design/

**Comment by vcristiani** [comment]
`@attr.s(frozen=True)
class Galaxy:
    x = attr.ib()
    y = attr.ib()
    z = attr.ib()
    vx = attr.ib()
    vy = attr.ib()
    vz = attr.ib()
    m = attr.ib()
    
    components = attr.ib(default=None)
    metadata = attr.ib()
    
    
    

g = Galaxy(x, y, z, vx, vy, vz, m, name="Sombrero")

g.plot()

g.j_


class Model:
    
    def split(self, glx):
        raise NotImplementedError()
    
    def chop(self, glx, *, y=None, z=None, vx=None, vy=None, vz=None, m=None):
        if isinstance(glx, Galaxy):
            if (y, z, vx, vy, vz, m) == (None, None, None, None, None, None):
                raise ValueError(".............")
        else:
            glx = Galaxy(x=glx, y, z....)
        
        gt = self.split(glx)
        gt.metadata["method"] = self.method_name
        return gt
    
    
@attr.s(frozen=True)
class Abadi(Model):
    
    method_name = "Abadi"
    
    bins = attr.ib(default=10)
    
    def split(self, glx):
        self.bins
        j = glx.j_
        


m = Abadi()

gt = m.chop(g)
gt = m.chop(x, y, z, vx, vy, vz, m)

g.components # => None
gt.components # => [.....]

gt.metadata["method"]
`

**Comment by BrunoSanchez** [comment]
I like this API design. 

_If I wear the skin of an user_:

1.  I would be able to tell from the first block what is your intention. From second block the right way to use it. 
2. Third block is a good shot at how to implement more than one model of dynamical decomposition, we would need to see it in action.
3. Fourth and last block, looks a reasonable way of making it extendable, and in my opinion provides a clear path for future developement. 

Let's make it happen.
