### ISSUE TITLE
Add here name of galaxychop modules

### ISSUE THREAD

**Issue by BrunoSanchez** [vcristiani/galaxy-chop#42]
https://github.com/vcristiani/galaxy-chop/blob/db8cc5fa5fd3605ce4a10d448f2f6e8f9da66ad9/setup.py#L74

**Comment by nvillagra** [comment]
I don't quite understand which modules you mean. The ones that appear in utils.py? @BrunoSanchez

**Comment by BrunoSanchez** [comment]
I refer to the modules contained in the package, something like this
```python
py_modules=["ez_setup", "utils", "galaxychop"]
```
