### ISSUE TITLE
potential energy calculation validation

### ISSUE THREAD

**Issue by leliel12** [vcristiani/galaxy-chop#64]
Asignar a @ornemarioni 

Juan BC, [29.10.20 22:33]
Es mas Ornela corre el fortran para un numero de particulas chico... digamos unos...  nose 500 esta bien

Juan BC, [29.10.20 22:33]
guarda los resultados y datos en un csv

Juan BC, [29.10.20 22:33]
todo junto mezcladito

Juan BC, [29.10.20 22:34]
y guardalo en una carpeta test_Data

Juan BC, [29.10.20 22:34]
despues implementa un test que levante eso, y valide que da igual

Juan BC, [29.10.20 22:34]
fijate en el repo de piedra mili hace algo parecido

Juan BC, [29.10.20 22:35]
mas bien... 100 es suficiente

**Comment by ornemarioni** [comment]
Validation of potential energy is fixed in branch issues#62

**Comment by ornemarioni** [comment]
Issue fixed
