### ISSUE TITLE
check manifest

### ISSUE THREAD

**Issue by leliel12** [vcristiani/galaxy-chop#71]
Los paquetes python deben incorporar licncias y readme ademas de su codigo fuente. esto se controla con el archivo `MANIFEST.in`

Existe un comando `check-manifest` el cual con la opcion "-c" genera un manifest para empezar a trabajar.

Agregar un environment (en tox y travis) *check-manifest*

```ini
[testenv:check-manifest]
skip_install = True
usedevelop = False
deps = check-manifest
commands =
    check-manifest
```

El manifest tiene que excluir documentacion, y tests pero incluir README y LICENSE

**Comment by BrunoSanchez** [comment]
This should be a simple commit to master.

**Comment by antotaverna** [comment]
Ok, I created the MANIFEST.in file and I added the check-manifest environment in tox.ini, but I have a error when I run tox -e check-manifest, and I can't fixit. 
------------------
lists of files in version control and sdist do not match!
missing from VCS:
  MANIFEST.in
no MANIFEST.in found
------------------

**Comment by antotaverna** [comment]
Fixed issue#71
