### ISSUE TITLE
Capacidad de transformar las galaxias en arrays 2d

### ISSUE THREAD

**Issue by leliel12** [vcristiani/galaxy-chop#81]
> Nota no podemos garantizar la funcionalidad de esto sin la correcta implementación de #80

> Nota esta funcionalidad es necesaria para interactuar con scikit-learn

- [x] El módulo `galaxychop/galaxychop.py` tiene que ser renombrado a `galaxychop/core.py`. Este módulo va a tener funcionalidades comunes a todo galaxychop (La clase `Galaxy` y el `GCDecomposeMixin` (ver issue #82).
- [x] Agregar el método `values()` a la clase `Galaxy` el cual deve devolver un array 2D, donde cada fila es una particula y cada columna es un atributo de la clase. Ejemplo: asumiendo que solo tenemos los atributos *x*, *y*, *z* en la clase:

``` python
class Galaxy:
    # codigo de galaxy
    def values(self):
        arr = np.vstack(
            hastack(self.arr_.x_s, np.arr_.x_g, self.arr_.x_dm),  # x
            hastack(self.arr_.y_s, np.arr_.y_g, self.arr_.y_dm),  # y
            hastack(self.arr_.z_s, np.arr_.z_g, self.arr_.z_dm)  # z
        )
        return arr.T
```

**Comment by RafaelPignata622** [comment]
closes with #91
