### ISSUE TITLE
Mezclar lista en el fixture

### ISSUE THREAD

**Issue by leliel12** [vcristiani/galaxy-chop#95]
https://github.com/vcristiani/galaxy-chop/blob/95b966c32a563e7a85d5990abdb83d93618d186c/tests/test_input.py#L424-L450

El codigo no empeora pero queda mas explicito

```python
@pytest.mark.parametrize(
    "shorten",  
    [ 
        "x_s", 
        "y_s", 
        "z_s", 
        "vx_s", 
        "vy_s", 
        "vz_s", 
        "m_s", 
        "x_g", 
        "y_g", 
        "z_g", 
        "vx_g", 
        "vy_g", 
        "vz_g", 
        "m_g", 
        "x_dm", 
        "y_dm", 
        "z_dm", 
        "vx_dm", 
        "vy_dm", 
        "vz_dm", 
        "m_dm", 
    ] 
) 
def test_same_size_inputs(shorten, random_galaxy_params): 
    pass
```

**Comment by ornemarioni** [comment]
Al principio lo hice asi como me decis y black se quejaba. Por eso opté por la lista afuera del parametrize

**Comment by ornemarioni** [comment]
> Al principio lo hice asi como me decis y black se quejaba. Por eso opté por la lista afuera del parametrize

No dije nada. Me faltaba una coma. Ya lo arregle
